### PR TITLE
simplified it a bit

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue # .

### CODE REVIEW

**Comment by brianteeman** [comment]
wait a second

**Comment by brianteeman** [comment]
Dont know why but this change isnt there and I am just too tired to investigate

+COM_JOOMLAUPDATE_VIEW_DEFAULT_INSTALL_SELF_UPDATE_FIRST="You must update to the latest version of the Joomla Update Component before you can install the Joomla Core Update!"

**Comment by zero-24** [comment]
Ok i can implement both. Thanks

**Comment by zero-24** [comment]
pushed the seccond fix with: https://github.com/joomla/joomla-cms/commit/9ff522088f23c235a0f25bf3607b4babf9e3b08b Thanks!

**Pull request merged**
