### PR TITLE
Change markup

### PR DESCRIPTION
**Pull request by Quy**

### CODE REVIEW

**Comment by zero-24** [comment]
hmm this

image

vs this
image


is expected?

Where the seccond image is the way it looks after this patch.

**Comment by Quy** [comment]
Yes. I assume `The minimum requirements are the following:` is a separate paragraph.
In your patch, there is a big vertical gap after the unordered list.

**Comment by zero-24** [comment]
Ah ok looks like i did not look correct.

**Comment by zero-24** [comment]
Thanks @Quy

**Pull request merged**
