### PR TITLE
run syntax check in all php versions

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
also use while cycle that seems faster

### CODE REVIEW

**Comment by zero-24** [comment]
Thanks but i'm not sure about the while if it should fail so that we get exit 1 and not the return code of the while loop. It is on my list for the next days :)

**Comment by andrepereiradasilva** [comment]
sure did not test (don't have travis to test) ...

**Comment by andrepereiradasilva** [comment]
BTW i think for hhvm you need to do `hhvm -l xxx`

**Comment by andrepereiradasilva** [comment]
will close this

**Pull request closed without merging**
