### PR TITLE
Patch 11

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
@zero-24 see this minor changes

### CODE REVIEW

**Comment by zero-24** [comment]
can you sync?

**Comment by andrepereiradasilva** [comment]
ok i see you already did most of changes so now this have conflicts. will close this.

I just made some other minor changes here, if you want make then in your PR too

**Comment by zero-24** [comment]
https://github.com/joomla/joomla-cms/pull/12266/commits/bb75f11ab60759cb462fbabd7816a4462705b81e

**Comment by zero-24** [comment]
Thanks @andrepereiradasilva :+1:

**Pull request closed without merging**
