### PR TITLE
fix for travis

### PR DESCRIPTION
**Pull request by wojsmol**
Pull Request for https://github.com/joomla/joomla-cms/pull/10438

### CODE REVIEW

**Comment by zero-24** [comment]
Thanks!

**Comment by wojsmol** [comment]
@zero-24 Plese merge

**Comment by zero-24** [comment]
Should be in now.

**Comment by zero-24** [comment]
Hmm guthub looks broken. I will try later again

**Comment by zero-24** [comment]
Ok now it is in thanks

**Pull request merged**
